resolver: lts-6.30
flags: {}

compiler: ghcjs-0.2.0.9006030_ghc-7.10.3
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006030_ghc-7.10.3:
         url: http://ghcjs.tolysz.org/lts-6.30-9006030.tar.gz
         sha1: 2371e2ffe9e8781808b7a04313e6a0065b64ee51

allow-newer: true

packages:
- .
- ../haskell-api-helpers-ghcjs
- ../haskell-api-helpers-shared
- ../lnforum-types-gen
#- ../ghcjs-ajax/ghcjs-ajax
# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps: []
flags: {}
extra-package-dbs: []
